cache_dir: cache
publication_bias:
  Axios: 3
  Economist: 2
  Refinery 29: 1
  The Verge: 2
  Washington Post: 2
  Business Insider: 3
  Fox News: 4
  New Republic: 1
  Reuters: 3
  TMZ: -1
  Wired: 3
  Buzzfeed News: 1
  Gizmodo: 2
  New Yorker: 1
  TechCrunch: 3
  Vice: 1
  CNBC: 3
  Hyperallergic: -1
  People: -1
  The Hill: 3
  Vice News: -1
  CNN: 2
  Mashable: -1
  Politico: 2
  The New York Times: 2
  Vox: 1
